# Generated by Django 4.0.5 on 2022-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='files/items')),
                ('content', models.TextField(null=True)),
                ('creator', models.CharField(default='Admin', max_length=20)),
                ('name', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/items')),
                ('content', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('company', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
