# Generated by Django 4.0.5 on 2022-11-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design_Desc',
        ),
        migrations.AddField(
            model_name='design_model',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='design_model',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='design_model',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design_model',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design_model',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
