# Generated by Django 4.0.5 on 2022-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_alter_design_model_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_model',
            name='image',
            field=models.ImageField(null=True, upload_to='files/items'),
        ),
    ]
