# Generated by Django 4.0.5 on 2022-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_design_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_model',
            name='creator',
            field=models.CharField(default='Admin', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='design_model',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
