# Generated by Django 4.0.5 on 2022-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_design_model_creator_design_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_model',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
