# Generated by Django 4.0.5 on 2022-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_alter_design_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_model',
            name='creator',
            field=models.CharField(default='Admin', max_length=20),
        ),
    ]
