# Generated by Django 4.0.5 on 2022-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_alter_design_model_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/items')),
                ('content', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('company', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
